#############################################################################
#
# makefile.due common settings for Arduino Due projects
#
# (c) Wouter van Ooijen (www.voti.nl) 2017
#
# This file is in the public domain.
# 
#############################################################################

# settings for Arduino Due projects
TARGET            := arduino_due
CONSOLE_BAUDRATE  := 115200

# defer to the Makefile.link
include           $(RELATIVE)/Makefile.link
